# Generated by Django 2.2.12 on 2022-02-25 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_assignment_tl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='first_work_done',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
